services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    volumes:
      - ./api-gateway:/usr/src/app     
    ports:
      - '3000:3000'
    depends_on:
      - orders-service
      - payments-service
    
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # RabbitMQ AMQP port
    
    networks:
      - app-network
      
  mongo-payments:
    image: mongo    
    ports:
      - '27017:27017'

    environment:
      - MONGODB_INITDB_ROOT_USERNAME=docker
      - MONGODB_INITDB_ROOT_PASSWORD=docker
    volumes:
      - mongo-payments-data:/data/db  
    networks:
      - app-network
    
    depends_on:
      - rabbitmq
  
  mongo-production:
    image: mongo    
    ports:
      - '27018:27017'

    environment:
      - MONGODB_INITDB_ROOT_USERNAME=docker
      - MONGODB_INITDB_ROOT_PASSWORD=docker
    volumes:
      - mongo-production-data:/data/db  
    networks:
      - app-network   
    depends_on:
      - rabbitmq 

  payments-service:
    build: 
      context: ./ms-payments-service
      dockerfile:  Dockerfile          
    container_name: payments_app    
    ports:
      - 3334:3334
      - 9230:9230 #porta para debug
    volumes:
      - ./src:/usr/src/app/src 

    environment:                  
      - APP_PORT=3334
      - DB_DATABASE=pagamentos      
      - MONGO_URI=mongodb://mongo-payments:27017/pagamentos
      - ORDERS_URI=http://orders-app:3333/api/v1
      - RABBITMQ_URL=amqp://rabbitmq
    
    depends_on:
      - mongo-payments
      - rabbitmq 

    networks:
      - app-network
  
  production-service:
    build: 
      context: ./ms-production-service
      dockerfile:  Dockerfile          
    container_name: production_app    
    ports:
      - 3335:3335
      - 9231:9231 #porta para debug
    volumes:
      - ./src:/usr/src/app/src 

    environment:                  
      - APP_PORT=3335
      - DB_DATABASE=producao      
      - MONGO_URI=mongodb://mongo-production:27017/producao      
      - RABBITMQ_URL=amqp://rabbitmq
    
    depends_on:
      - mongo-production
      - rabbitmq 

    networks:
      - app-network

  orders-service:
    build: 
      context: ./ms-orders-service
      dockerfile: Dockerfile          
    container_name: orders_app    
    ports:
      - 3333:3333
      - 9229:9229 #porta para debug
    volumes:
      - ./src:/usr/src/app/src 

    environment:                  
      - APP_PORT=3333
      - DB_DATABASE=pedidos_db
      - DB_USER=docker
      - DB_PASS=docker
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - RABBITMQ_URL=amqp://rabbitmq

    depends_on:
      - postgres-db
      - rabbitmq

    networks:
      - app-network
  
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pedidos_db
    volumes:
      - pgdata:/data/postgres
      
    networks:
      - app-network
    depends_on:
      - rabbitmq

networks:
  app-network:
    driver: bridge

volumes:
  mongo-payments-data:
    driver: local
  mongo-production-data:
    driver: local
  pgdata:
    driver: local      